export const types = {
  FETCH_CHARACTERS_REQUEST: "FETCH_CHARACTERS_REQUEST",
  FETCH_CHARACTERS_SUCCESS: "FETCH_CHARACTERS_SUCCESS",
  FETCH_CHARACTERS_FAILURE: "FETCH_CHARACTERS_FAILURE",

  FETCH_EPISODES_REQUEST: "FETCH_EPISODES_REQUEST",
  FETCH_EPISODES_SUCCESS: "FETCH_EPISODES_SUCCESS",
  FETCH_EPISODES_FAILURE: "FETCH_EPISODES_FAILURE",
};
