export const types = {
  FETCH_CHARACTERS_REQUEST: "FETCH_CHARACTERS_REQUEST",
  FETCH_CHARACTERS_SUCCESS: "FETCH_CHARACTERS_SUCCESS",
  FETCH_CHARACTERS_FAILURE: "FETCH_CHARACTERS_FAILURE",

  FETCH_SINGLE_CHARACTER_REQUEST: "FETCH_SINGLE_CHARACTER_REQUEST",
  FETCH_SINGLE_CHARACTER_SUCCESS: "FETCH_SINGLE_CHARACTER_SUCCESS",
  FETCH_SINGLE_CHARACTER_FAILURE: "FETCH_SINGLE_CHARACTER_FAILURE",
  RESET_SINGLE_CHARACTER: "RESET_SINGLE_CHARACTER",

  FETCH_EPISODES_REQUEST: "FETCH_EPISODES_REQUEST",
  FETCH_EPISODES_SUCCESS: "FETCH_EPISODES_SUCCESS",
  FETCH_EPISODES_FAILURE: "FETCH_EPISODES_FAILURE",
};
